# Generated by Django 3.0.7 on 2022-06-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150, verbose_name='nombre')),
                ('apellidos', models.TextField(max_length=150, verbose_name='apellidos')),
                ('rut', models.TextField(max_length=10, verbose_name='rut')),
            ],
        ),
    ]
