# Generated by Django 3.0.7 on 2022-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.TextField(max_length=150, verbose_name='Nombre Producto')),
                ('Valor', models.FloatField(max_length=150, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=150, verbose_name='Fecha Reserva')),
                ('Hora', models.TimeField(max_length=150, verbose_name='Hora Reserva')),
                ('direccion', models.TextField(max_length=150, verbose_name='Direccion')),
                ('telefono', models.IntegerField(max_length=150, verbose_name='Telefono')),
                ('observacion', models.TextField(max_length=150, verbose_name='Obervacion')),
                ('Valor', models.FloatField(max_length=150, verbose_name='Valor reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.TextField(max_length=150, verbose_name='Tipo de Servicio')),
                ('Valor', models.IntegerField(max_length=150, verbose_name='Precio')),
            ],
        ),
    ]
